#!/usr/bin/env bash
# Installing nginx web server
echo "Updating package lists..."
sudo apt-get update -y -qq
echo "Installing nginx..."
sudo apt-get install nginx -y
echo "Starting nginx service..."
sudo service nginx start
sudo ufw allow 'Nginx HTTP'
sudo chown -R "$USER":"$USER" /var/www/html
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp
echo -e "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
sudo sed -i "/server_name _;/a \        location /redirect_me {\n       return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n       }" /etc/nginx/sites-available/default

sudo service nginx restart
