#!/usr/bin/env bash
#This script displays "Best School" 10 times and in (9th) line Hi using while loop and if statement

count=0

while [ $count -lt 10 ]
do
    echo "Best School"
    if [ $count -eq 8 ]
    then
        echo "Hi"
    fi
    ((count++))
done