#!/usr/bin/env bash
#modify hosts to configure localhost and facebook.com

if [ "$EUID" -ne 0 ] 
then
	echo "Please run this script as root or with sudo."
	exit 1
fi
cp /etc/hosts ~/etc/hosts.bak
echo "127.0.0.2	localhost" >> /etc/hosts
echo "8.8.8.8	facebook.com" >> /etc/hosts